apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
        - name: core
          image: core
          imagePullPolicy: Never
          env:
          - name: APP_PORT
            value: "3000"
          - name: APP_DATABASE_HOST
            value: "core-mariadb-srv"
          - name: APP_DATABASE_USER
            value: "root"
          - name: APP_DATABASE_PASS
            value: "123456"
          - name: APP_DATABASE_NAME
            value: "database_development"
          - name: JWT_SECRET
            value: "cvbd345wsdfsdtg"
---
apiVersion: v1
kind: Service
metadata:
  name: core-srv
spec:
  selector:
    app: core
  ports:
    - name: core
      protocol: TCP
      port: 3000
      targetPort: 3000